import Head from 'next/head'
import Footer from './footer';
import Header from './header';
import { Fragment } from "react"
import styles from './layout.module.scss';

function Layout(props) {
  return (
    <Fragment>
      <Head>
        <title>Kang&apos;s Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css" />
      </Head>
      <Header />
      <main className={styles.main}>{props.children}</main>
      <Footer />
    </Fragment>
  )
}

export default Layout;
